### ISSUE TITLE
Incorrect cmake configuration for different x86_64 processors

### ISSUE THREAD

**Issue by bmx666** [mozilla/aom#2]
Many old processors don't support all of those instructions: sse, sse2, sse3, sse4.1, avx, avx2.
Cmake script enables all instructions but it's completely wrong.

If disable all instructions then compilation fail with **undefined reference to...** in **av1_rtcd.h** and **aom_dsp_rtcd.h**

**Comment by luctrudeau** [comment]
Thanks for reporting this. This repository is currently not up to date with the official aim project. You can get the latest version of libaom at https://aomedia.googlesource.com/aom/ 
This project should soon be updated to match

**Comment by luctrudeau** [comment]
If you look upstream
 https://aomedia.googlesource.com/aom/+/727ffdb617fcc57a3b9d602aba49e95eaa499c9b/build/cmake/cpu.cmake#91

We loop over all the X86 flavors and add the ones that are compatible with the CPU.

To disable all instructions use the following:
cmake path/to/aom -DAOM_TARGET_CPU=generic

**Comment by bmx666** [comment]
@luctrudeau, thanks. It's exactly what are required.
