### ISSUE TITLE
compiline VLC for Android fails

### ISSUE THREAD

**Issue by cloned2k16** [mozilla/aom#5]
compiling VLC traget arm64 ABI ...
somehow fals into compiling for an x86

In file included from
vlc-android/vlc/contrib/contrib-android-aarch64-linux-android/aom/aom_build/config/aom_dsp_rtcd.h:1721:

vlc-android/vlc/contrib/contrib-android-aarch64-linux-android/aom/aom_ports/x86.h:50:26: note:
      expanded from macro 'cpuid'
                       : "=a"(ax), "=b"(bx), "=c"(cx), "=d"(dx) \
                         ^

vlc-android/vlc/contrib/contrib-android-aarch64-linux-android/aom/aom_ports/x86.h:192:3: error:
      invalid output constraint '=a' in asm
  cpuid(1, 0, reg_eax, reg_ebx, reg_ecx, reg_edx);
  ^

vlc-android/vlc/contrib/contrib-android-aarch64-linux-android/aom/aom_ports/x86.h:215:9: error:
      invalid output constraint '=a' in asm
        cpuid(7, 0, reg_eax, reg_ebx, reg_ecx, reg_edx);
        ^

vlc-android/vlc/contrib/contrib-android-aarch64-linux-android/aom/aom_ports/x86.h:233:38: error:
      invalid output constraint '=a' in asm
  __asm__ __volatile__("rdtsc\n\t" : "=a"(tsc) :);
                                     ^

vlc-android/vlc/contrib/contrib-android-aarch64-linux-android/aom/aom_ports/x86.h:251:34: error:
      invalid output constraint '=a' in asm
  __asm__ __volatile__("rdtsc" : "=a"(lo), "=d"(hi));
                                 ^
5 errors generated.

**Comment by rillian** [comment]
Hi. This fork isn't being maintained and doesn't match the final design of the codec. You might prefer to work with the [upsteam source](https://aomedia.googlesource.com/aom/) or port to the new [rav1e](https://github.com/xiph/rav1e) and [dav1d](https://code.videolan.org/videolan/dav1d) implementations, which are much faster than the aom code.
